##除了application.properties配置文件，还有yami配置文件，后缀名为yml或yaml类型
##如果两个文件都有，取两个文件的并集，如果有冲突，以properties为主
jdbc:
  driverClassName : com.mysql.jdbc.Driver
  url : jdbc:mysql//localhost:3307/taotao
  username : root
  password : root